### Recuperar todos las operaciones
GET http://localhost:8080/trades

### Recuperar todos las operacionesfiltradas por Criptomoneda
GET http://localhost:8080/trades/BTC

### Recuperar todos las compras
GET http://localhost:8080/trades/compras

### Recuperar todos las ventas
GET http://localhost:8080/trades/ventas

### Crear una operación de compra
POST http://localhost:8080/trades
Content-Type: application/json

{
  "tipo_operacion":"compra",
  "cripto": "BTC",
  "precio_usdt": 2500,
  "cantidad_cripto": 0.0054,
  "cantidad_usdt": 1000,
  "fecha": "2020-01-01"
}

### Actualizar operación mediante un ID
PATCH http://localhost:8080/trades/1
Content-Type: application/json

{
  "cantidad_usdt": 2022
}
